-- Collision Groups
GROUP_PLAYER = 0x01
GROUP_BULLET = 0x02
GROUP_ENEMY  = 0x04

SPRITE_TAGS = {
    player = 1,
    playerBullet = 2,
    asteroid = 3,
    enemy = 4,
    enemyBullet = 5,
    enemyBase = 6,
}

-- World gameplay occurs in (minus the dashboard)
VIEWPORT_WIDTH = 400 - 80
VIEWPORT_HEIGHT = 240

HALF_VIEWPORT_WIDTH = VIEWPORT_WIDTH >> 1
HALF_VIEWPORT_HEIGHT = VIEWPORT_HEIGHT >> 1

MINIMAP_WIDTH = 9
MINIMAP_HEIGHT = 12

WORLD_WIDTH = 320 * MINIMAP_WIDTH
WORLD_HEIGHT = 240 * MINIMAP_HEIGHT

WORLD_PLAYER_STARTX = WORLD_WIDTH >> 1
WORLD_PLAYER_STARTY = WORLD_HEIGHT >> 1